[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x"]

[phases.install]
cmds = ["npm ci --production=false"]

[phases.build]
cmds = [
  "cd packages/database && npm install && npx prisma generate && npm run build",
  "cd ../../apps/admin && npm install && npm run build",
  "cd ../api && npm install && npm run build"
]

[start]
cmd = "cd apps/api && node dist/index.js"
